export const VALIDATE_EMAIL_INPUT_LOGIN_FORM    = 'VALIDATE_EMAIL_INPUT_LOGIN_FORM';
export const VALIDATE_PASSWORD_INPUT_LOGIN_FORM = 'VALIDATE_PASSWORD_INPUT_LOGIN_FORM';
export const VALIDATE_INPUT_SUCCESS_CLASS       = 'has-success';
export const VALIDATE_INPUT_ERROR_CLASS         = 'has-error';
export const VALIDATE_INPUT_WARRNING_CLASS      = 'has-warrning';